version: '3.1'

services:   
      
  kafka1:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - /path/to/kafka-persistence:/engaze/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS:evento:3:1:compact     
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092 
    depends_on:
      - zookeeper1

    networks:
      - engaze-network    
 
networks:
  engaze-network:
    external:
      name: eventstore_engaze-network   
