version: '3.1'

services: 
  
  event-store:
    image: eventstore/eventstore
    restart: always
    container_name: eventstore
    hostname: event-store
    networks:
      - engaze-network
    volumes:
      - 'eventowrite_eventstore_db:/usr/share//eventowrite/data/db'
      - 'eventowrite_eventstore_log:/usr/share//eventowrite/data/log'  
    ports:
      - "2113:2113"
      - "1113:1113"    
    
  eventowrite:
    image: eventowrite
    restart: always
    container_name: eventowrite
    hostname: evento-write
    ports:
      - '5000:5000'
    volumes:
      - 'eventowrite_api:/usr/share//eventowrite/log'
    environment:     
      - EVENTSTORE_CONNSTRING="tcp://event-store:1113"
    networks:
      - engaze-network
      
  zoo-publishservice:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    networks:
      - engaze-network
    volumes:
      - 'zookeeper_data:/usr/share/zookeeper'
 
  kafka-publishservice:
    image: 'bitnami/kafka:0'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/usr/share//kafka'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo-publishservice:2181
      - KAFKA_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS:test:3:1:compact     
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.102:9092
      
    networks:
      - engaze-network
      
  
networks:
  engaze-network:
    driver: bridge
    
volumes:
  eventowrite_api:
  eventowrite_eventstore_db:
  eventowrite_eventstore_log:
  kafka_data:
  zookeeper_data: